import Head from "next/head";
import Image from "next/image";
import formImage from "../public/contact_us.svg"
import { Formik, useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import {motion as m} from 'framer-motion'

export default function Home() {

  //Router
  const router = useRouter(); 


  //Formik Logics
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "None Selected",
      contact: "",
      message: "",
      terms: "",
    },

    //Validate Form
    validationSchema: Yup.object({
      name: Yup.string()
                .max(50, 'Name must be 50 character of less')
                .required('Name is required'),
      email: Yup.string()
                .email('Invalaid email address')
                .required('Email is required'),
      // contact: Yup.string()
      //           .max(10, 'Contact must be of 10 digits')
      //           .required('Contact is required'),
      terms: Yup.array()
                .required('Terms of service must be checked'),
    }),

    //Submit Form
    onSubmit: (values) => {
      console.log(values);
      router.push({pathname: "/success", query: values})
    }
  });

  // console.log(formik.errors);

    return (
    <m.div 
      initial={{opacity: 0}} 
      animate={{opacity: 1}}
      exit={{opacity: 0}}
      className="absoulte w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form 
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg font-latoRegular">
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-latoBold">
              Let's get started
            </h1>
            <p className="text-lg text-gray-500">
              Join our E-learning platform today and unlock over 500+ courses 
              and digital assests ready to download
            </p>
            <div className="mt-6">
              {/* Name */}
              <div className="pb-4">
                <label className={`block font-latoBold text-sm pb-2 
                                  ${formik.touched.name && formik.errors.name ? "text-red-400" : ""}`} 
                                  htmlFor="name"
                                  >
                  {formik.touched.name && formik.errors.name ? formik.errors.name : "Name"}
                </label>
                <input 
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-black focus:ring-black" 
                  type="text" 
                  name="name" 
                  value = {formik.values.name}
                  onChange= {formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder="Enter your name"
                />
              </div>
              {/* Email */}
              <div className="pb-4">
                <label className={`block font-latoBold text-sm pb-2 
                                  ${formik.touched.email && formik.errors.email ? "text-red-400" : ""}`} 
                                  htmlFor="email">
                  {formik.touched.email && formik.errors.email 
                    ? formik.errors.email 
                    : "Email"}
                </label>
                <input 
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-black focus:ring-black" 
                  type="email" 
                  name="email" 
                  value = {formik.values.email}
                  onChange= {formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder="Enter your email"
                />
              </div>
              {/* Country Code */}
              <div className="flex flex-col md:flex-row items-center">
                <div className="flex items-center mb-4 md:mb-0 pb-4">
                  <label 
                    className={`block font-latoBold text-sm mt-2 mr-2 justify-center
                    ${formik.touched.country && formik.errors.country ? "text-red-400" : ""}`} 
                    htmlFor="country_code">
                    {formik.touched.country && formik.errors.country
                      ? formik.errors.country 
                      : "Country Code "}
                  </label>
                  <select
                    className="border-2 border-gray-500 pb-2 mt-2 rounded-md w-full focus:border-black focus:ring-black"
                    id="countryCode"
                    name="countryCode"
                    value = {formik.values.country}
                    onChange= {formik.handleChange}
                    onBlur={formik.handleBlur}
                  >
                    <option value="+91">🇮🇳 +91</option>
                    <option value="+44">🇬🇧 +44</option>
                    <option value="+86">🇨🇳 +86</option>
                    <option value="+880">🇧🇩 +880</option>
                    <option value="+1">🇺🇸 +1</option>
                  </select>
                </div>
                {/* Contact */}
                <div class="flex items-center">
                  <label 
                    className={`block font-latoBold text-sm mx-2 mb-2 justify-center
                    ${formik.touched.contact && formik.errors.contact ? "text-red-400" : ""}`} 
                    htmlFor="contact">
                    {formik.touched.contact && formik.errors.contact
                      ? formik.errors.contact 
                      : "Contact"}
                  </label>
                  <input
                    className="border-2 border-gray-500 pb-2 mb-2 rounded-md w-full focus:border-black focus:ring-black"
                    type="text"
                    id="contact"
                    name="contact"
                    placeholder="Enter your contact"
                    value = {formik.values.contact}
                    onChange= {formik.handleChange}
                    onBlur={formik.handleBlur}
                  />
                </div>
              </div>
              {/* Message */}
              <div className="flex items-center mt-2">
                <label 
                  className="mr-2 text-black w-1/2"
                  htmlFor="message">Message</label>
                <textarea
                  className="w-full h-auto px-2 py-1 border-2 border-gray-500 p-2 rounded-md focus:border-black focus:ring-black"
                  id="message"
                  name="message"
                  value = {formik.values.message}
                  onChange= {formik.handleChange}
                  onBlur={formik.handleBlur}
                ></textarea>
              </div>
              {/* Terms of Service */}
              <div className="pb-4">
                <label className={`block font-latoBold text-sm pb-2 
                                  ${formik.touched.terms && formik.errors.terms ? "text-red-400" : ""}`}  
                                  htmlFor="terms">
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : "Terms of Service "}
                </label>
                <div className="flex items-center gap-2">
                  <input 
                    type="checkbox" 
                    name="terms" 
                    value= "checked"
                    onChange= {formik.handleChange}
                    className="h-5 w-5 text-black focus:border-black focus:ring-black" 
                  />
                  <p className="text-lg text-gray-500">
                    I agree to the Terms and Servicce that my data will be taken and sold.
                  </p>
                </div>
              </div>
              <button 
                type="submit" 
                className="bg-black font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full">
                  Start Learnig today!
              </button>
            </div>
          </div>
          <div className="relative flex-1">
            <Image 
              alt="form-learn"
              src={formImage} 
              fill 
              priority 
              className="objecct-cover rounded-lg p-4"
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
